# Generated by Django 4.2.5 on 2023-09-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
