# Generated by Django 4.2.5 on 2023-09-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_service', '0006_room_sms_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='sender_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sms',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sms_service.room'),
        ),
    ]
