version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    container_name: my_db
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/service2/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=037700
      - POSTGRES_DB=postgres
  service2:
    container_name: service2
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - 8090:8090
    env_file:
      docker/.env
    depends_on:
      - db
  redis:
    image: 'redis:alpine'
    hostname: redis
    container_name: redis
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/worker-entrypoint.sh
    env_file:
      docker/.env
    links:
      - redis
    depends_on:
      - redis
      - service2
      - db
volumes:
  postgres_data: